version: "3"

services:
  tc-server:
    image: jetbrains/teamcity-server:2017.2.2
    environment:
      - "TEAMCITY_SERVER_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    networks:
      - teamcity
    ports:
      - "5005:5005"
      - "8111:8111"
    volumes:
#      - tc-server
      - ./data/tc-server/datadir:/data/teamcity_server/datadir
      - ./data/tc-server/sync:/sync
  tc-agent:
    image: jetbrains/teamcity-minimal-agent:2017.2.2
    environment:
      - "SERVER_URL=http://tc-server:8111"
      - "AGENT_NAME=agent-1"
    networks:
      - teamcity
    ports:
      - "9090:9090"
    volumes:
#      - tc-agent
      - ./data/tc-agent/conf:/data/teamcity_agent/conf
      - ./data/tc-agent/sync:/sync

networks:
  teamcity:
#    external: true

#volumes:
#  tc-server:
#    external: true
#  tc-agent:
#    external: true
