---
name: Release
on:
  release:
    types:
      - released

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish to GitHub Packages
        run: ./gradlew clean build publishAllPublicationsToGitHubPackagesRepository --no-daemon --info --stacktrace
        env:
          PACKAGE_REGISTRY_USER: ${GITHUB_ACTOR}
          PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Jetbrains Marketplace
        run: ./gradlew clean build publishPlugin -x check --no-daemon --info --stacktrace
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
...
